import type { Metadata } from "next";
import styles from "@/sass/styles.module.scss";
import Header from "@/components/Layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={styles.app}>
        <Header />
        {children}
      </body>
    </html>
  );
}
